-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQge/x0Gusr7NTvPIVy
JbSyVY2g6XndEHXrKa+pf+GmDRmgCgYIKoZIzj0DAQehRANCAARPbe85J+fKcaah
9VRJXyB1n+/SWRnvH0w1lGJXARwWNlnoMVRFDBM957VJvGu7VMDFf71V0NHpqjSP
QP38FFVW
-----END PRIVATE KEY-----